### ISSUE TITLE
Redirect URI

### ISSUE THREAD

**Issue by Err0r404** [krisrak/jquery-cordova-oauth2#5]
Hi,

I'm trying to make my very first Cordova App and encounter a problem with oauth2 :
After using your plugin a new window appear where I can allow or deny my app but right after clicking the authorization button I'm redirected to the URI and not the application...

Tested on web browser (without Cordova compliation) and Android phone (with Cordova compilation)

Did I miss something ?

**Comment by martincarvalho** [comment]
I've been trying to learn and work with phonegap for the last couple days and had a similar problem.
I installed the plugin correctly, latest cordova version, testing on android device and all.. After struggling with this issue for hours, I noticed that most examples had a link to cordova.js file and I didn't, just then I went over to the documentation and then understood what was going on...
I know it's dumb, but hope this helps others.

**Comment by indrapermanarusli** [comment]
I am using cordova 5.1.1, so how to install and use the plugin? I am trying to use:
cordova plugin add https://github.com/krisrak/jquery-cordova-oauth2

Response:
Repository "https://github.com/krisrak/jquery-cordova-oauth2" checked out to git ref "master"
Error: ENOENT, no such file or directory

**Comment by krisrak** [comment]
@indrapermanarusli this is not cordova plugin, its a jquery plugin for cordova app, just include script and make calls like in example, you have to include in-app-browser cordova plugin and build cordova app. check the example code

**Comment by joomlaevolved** [comment]
Hi there.  And thank you for your nice library.

I am using this library  implicit call for a custom service of mine.

The problem is that I cannot get it to close the inappbrowser.

I have even tried 	window.open('','_self').close(); or window.close(); after the authentication takes place but I get a 

"Scripts may close only the windows that were opened by it."

Do you have any idea on how to close the inappbrowser and therefore fire the callback function of the oauth2?

Thank you!
